### ISSUE TITLE
Algolia CLI

### ISSUE THREAD

**Issue by anaibol** [algolia/algoliasearch-client-cmd#5]
Hi! Is there a new Algolia CLI? Like for clearing an index via command line?

Thanks!

**Comment by redox** [comment]
> Hi! Is there a new Algolia CLI? Like for clearing an index via command line?
> 
> Thanks!

Hi @anaibol,

we actually just deprecated this command-line API client because it wasn't really used and it was pretty hard to maintain advanced features/options that are not CLI-friendly.

Ideally, I would recommend you to create a small script in ruby/python/php/go/javascript to do what you need. It's not a lot of code and it is way more convenient as soon as it comes to JSON processing & error handling.

Would that work for you?

**Comment by anaibol** [comment]
Cool, but I would prefer an official command line tool..
Thanks anyway!

**Comment by redox** [comment]
> Cool, but I would prefer an official command line tool..
> Thanks anyway!

Maybe the easiest would be to reduce the current scope and restrict it to be a small wrapper on top of cURL, only implementing Algolia's [retry-strategy](https://www.algolia.com/doc/rest-api/search#quick-reference)

**Comment by redox** [comment]
@anaibol I've just pushed a new/simple version of the command-line API client to the `master` branch: only wrapping cURL.

Would that work for you?

**Comment by anaibol** [comment]
Cool, I will try it :)
